<?php

namespace backend\models;

use Yii;
use yii\db\Query;
use yii\web\UnauthorizedHttpException;

class DocumentHeader extends \common\models\DocumentHeader
{
  public function fields()
  {
    return [
      'id',
      'customer_name' => 'CustomerName',
      'customer_id',
      'docnr',
      'store_name' => 'StoreName',
      'type', 'store_id'
    ];
  }

  public function getCustomerName()
  {
    return $this->customer->name;
  }

  public function getStoreName()
  {
    return  $this->store->name;
  }

  public static function find()
  {
    $userId = Yii::$app->user->id;
    $orders = (new Query())->select('order_id')->from('work_order')->where(['user_id' => $userId]);
    $find = parent::find()->andWhere(['id' => $orders]);
    return $find; // TODO: Change the autogenerated stub
  }
}
