<?php

namespace backend\models;

use Yii;
use yii\db\Query;
use yii\web\UnauthorizedHttpException;

class Store extends \common\models\Store
{
  public function fields()
  {
    return ['id', 'name'];
  }


  public static function find()
  {
    $userId = Yii::$app->user->id;
    $stores = (new Query())->select('store_id')->from('store_user')->where(['user_id' => $userId]);
    $find = parent::find()->andWhere(['id' => $stores]);
    return $find; // TODO: Change the autogenerated stub
  }
}
