<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "config_label".
 *
 * @property int $id
 * @property int|null $type_id
 * @property string|null $name
 * @property string|null $description
 * @property int|null $config_id
 * @property int|null $reference_id
 * @property string|null $serialty
 * @property string|null $labelty
 * @property int|null $usernr
 * @property float|null $epsilon
 * @property int|null $qtColumns
 * @property int|null $typeAux
 * @property int|null $time
 * @property int|null $status
 * @property string $created_at
 * @property string|null $updated_at
 *
 * @property Config $config
 * @property Reference $reference
 * @property SerialRules $serialRule
 * @property SerialType $type
 * @property User $usernr0
 */
class ConfigLabel extends \yii\db\ActiveRecord
{

  public $serialList;
  public $typeAux;

  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'config_label';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
      [['type_id', 'config_id', 'reference_id', 'usernr', 'qtColumns', 'time', 'status'], 'integer'],
      [['created_at', 'updated_at', 'serialList', 'typeAux'], 'safe'],
      [['serialty'], 'string'],
      [['time'], 'integer', 'skipOnEmpty' => false, 'min' => 5, 'tooSmall' => 'El Tiempo no puede ser Menor a 5'],
      [['epsilon'], 'number'],
      [['epsilon'], 'integer', 'skipOnEmpty' => false, 'min' => 100, 'tooSmall' => 'El Epsilon no puede ser Menor a 100'],
      [['name', 'description'], 'string', 'max' => 255],
      [['name', 'description'], 'required'],
      [['labelty'], 'string', 'max' => 2],
      [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => SerialType::className(), 'targetAttribute' => ['type_id' => 'id']],
      [['usernr'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['usernr' => 'id']],
      [['config_id'], 'exist', 'skipOnError' => true, 'targetClass' => Config::className(), 'targetAttribute' => ['config_id' => 'id']],
      [['reference_id'], 'exist', 'skipOnError' => true, 'targetClass' => Reference::className(), 'targetAttribute' => ['reference_id' => 'id']],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
      'id' => Yii::t('app', 'ID'),
      'type_id' => Yii::t('app', 'Type ID'),
      'name' => Yii::t('app', 'Name'),
      'description' => Yii::t('app', 'Description'),
      'config_id' => Yii::t('app', 'Config ID'),
      'reference_id' => Yii::t('app', 'Reference ID'),
      'dateto' => Yii::t('app', 'Dateto'),
      'datefrom' => Yii::t('app', 'Datefrom'),
      'serialchk' => Yii::t('app', 'Serialchk'),
      'sr_start' => Yii::t('app', 'Sr Start'),
      'sr_length' => Yii::t('app', 'Sr Length'),
      'serialty' => Yii::t('app', 'Serialty'),
      'labelty' => Yii::t('app', 'Labelty'),
      'usernr' => Yii::t('app', 'Usernr'),
      'epsilon' => Yii::t('app', 'Epsilon'),
      'qtColumns' => Yii::t('app', 'Qt Columns'),
      'time' => Yii::t('app', 'Time'),
      'status' => Yii::t('app', 'Status'),
      'created_at' => Yii::t('app', 'Created At'),
      'updated_at' => Yii::t('app', 'Updated At'),
    ];
  }

  /**
   * Gets query for [[Config]].
   *
   * @return \yii\db\ActiveQuery
   */
  public function getConfig()
  {
    return $this->hasOne(Config::className(), ['id' => 'config_id']);
  }

  /**
   * Gets query for [[Reference]].
   *
   * @return \yii\db\ActiveQuery
   */
  public function getReference()
  {
    return $this->hasOne(Reference::className(), ['id' => 'reference_id']);
  }

 
  /**
   * Gets query for [[Type]].
   *
   * @return \yii\db\ActiveQuery
   */
  public function getType()
  {
    return $this->hasOne(SerialType::className(), ['id' => 'type_id']);
  }

  /**
   * Gets query for [[Usernr0]].
   *
   * @return \yii\db\ActiveQuery
   */
  public function getUsernr0()
  {
    return $this->hasOne(User::className(), ['id' => 'usernr']);
  }

  public function beforeSave($insert)
  {
    if ($this->serialList) {

      $this->serialty = json_encode($this->serialList);
      $data= json_decode($this->serialty , true );

      $this->type_id= $data[$this->typeAux];
    }

    if($this->type_id == NULL){
      return  Yii::$app->session->setFlash(\dominus77\sweetalert2\Alert::TYPE_ERROR, [
        [
          'title' => 'Serial Principal Inválido',
          'timer' => 2000,
          'confirmButtonText' => 'Continuar!',
        ]
      ]);
    }else{
      return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
  }

  public function afterFind()
  {
    $this->serialList = json_decode($this->serialty, true);
    parent::afterFind();
  }
}
