<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  '
                    0-pending,
                    1-published,
                    2-spam
                ' => '
                0-pendiente,
                1-publicado,
                2-spam',
  '
                    0-pending,
                    1-published,
                    2-spam
                ' => ' 
                0-pendiente,
                1-publicado,
                2-spam',
  '<a href="{url}">Log in</a> to post a comment.' => '<a href="{url}"> Inicie sesión </a> para publicar un comentario.',
  'Are you sure you want to delete this item?' => "¿Está seguro de que desea eliminar este elemento?",
  'As' => 'Como',
  'Cancel' => 'Cancelar',
  'Comment has been added successfully.' => "El comentario se ha añadido correctamente",
  'Comments' => 'Comentarios',
  'Content' => 'Contenido',
  'Created At' => 'Creado en',
  'Created By' => 'Creado por',
  'Delete' => 'Borrar',
  'Email' => 'Correo electrónico',
  'Hide' => 'Esconder',
  'ID' => 'ID',
  'Ip' => 'Ip',
  'Language' => 'Idioma',
  'Main Parent ID' => 'ID principal del padre',
  'Model' => 'Modelo',
  'Model Key' => 'Llave de modelo',
  'Name' => 'Nombre',
  'Parent ID' => 'ID de los padres',
  'Post' => 'Correo',
  'Reply' => 'Respuesta',
  'Save' => 'Guardar',
  'Share your thoughts...' => 'Comparte tus pensamientos...',
  'Sorry, something went wrong. Please try again later.' => 'Perdón, algo salió mal. Por favor, inténtelo de nuevo más tarde.',
  'Update' => 'Actualizar',
  'Update {modelClass}: ' => 'Actualizar {modelClass}:',
  'Updated At' => 'Actualizado en',
  'Updated By' => 'Actualizado por',
  'Url' => "Url",
];
