<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'Abort any changes and reset settings' => 'Abortar los cambios y restablecer la configuración',
  'Apply' => 'Aplicar',
  'Are you sure you want to delete the setting?' => "¿Está seguro de que desea eliminar la configuración?",
  'Configure Order and Display of Grid Columns' => 'Configurar orden y visualización de columnas de cuadrícula',
  'Default Filter' => 'Filtro predeterminado',
  'Default Sort' => 'Orden predeterminado',
  'Delete' => 'Borrar',
  'Filter Configuration' => 'Configuración de filtro',
  'Filter Name' => 'Nombre de filtro',
  'Grid Theme' => 'Tema de cuadrícula',
  'Hidden / Fixed Columns' => 'Columnas ocultas / fijas',
  'Integer between {min} to {max}' => 'Entero entre {min} y {max}',
  'NOTE: When editing an existing record, both the {category} name and its settings will be modified.' => 'NOTA: Al editar un registro existente, se modificarán tanto el nombre de la {category} como su configuración',
  'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings).' => 'NOTA: Al editar un registro existente, solo se modificará el nombre de la {category} (y no la configuración).',
  'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '¡Operación no permitida! Se detectó una firma de solicitud no válida para la configuración de dynagrid. {params} ',
  'Page Size' => 'Tamaño de página',
  'Personalize Grid Configuration' => 'Personalizar la configuración de la cuadrícula',
  'Personalize grid settings' => 'Personalizar la configuración de la cuadrícula',
  'Remove saved grid settings' => 'Eliminar la configuración de cuadrícula guardada',
  'Reset' => 'Reiniciar',
  'Save' => 'Guardar',
  'Save / Edit Grid {title}' => "Guardar / editar cuadrícula {title}",
  'Save / edit grid {category}' => "Guardar / editar cuadrícula {category}",
  'Save grid settings' => 'Guardar configuración de cuadrícula',
  'Saved Filters' => 'Filtros Guardados',
  'Saved Sorts' => 'Clasificaciones guardadas',
  'Saving and applying configuration' => 'Guardar y aplicar la configuración',
  'Select a filter...' => 'Seleccione un filtro ...',
  'Select a sort...' => 'Seleccione un tipo ...',
  'Select a theme...' => 'Selecciona un tema...',
  'Select theme to style grid' => 'Seleccionar tema para diseñar la cuadrícula',
  'Select...' => 'Seleccione...',
  'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Establezca un nombre para guardar el estado de su cuadrícula actual {category}. Alternativamente, puede seleccionar una {category} guardada de la lista a continuación para editar o eliminar.',
  'Set default grid filter criteria' => 'Establecer criterios de filtro de cuadrícula predeterminados',
  'Set default grid sort criteria' => 'Establecer criterios de clasificación de cuadrícula predeterminados',
  'Sort Configuration' => 'Ordenar configuración',
  'Sort Name' => 'Ordenar nombre',
  'Trash' => 'Basura',
  'Trashing all personalizations' => 'Deshacer todas las personalizaciones',
  'Visible Columns' => 'Columnas visibles',
  'ascending' => 'ascendente',
  'descending' => 'descendente',
  'filter' => 'filtrar',
  'grid' => 'cuadricula',
  'rows per page' => 'filas por página',
  'sort' => 'ordenar',
];
