<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'CSV' => 'CSV',
  'Column' => 'Columna',
  'Comma Separated Values' => 'Valores Separados por Comas',
  'Disable any popup blockers in your browser to ensure proper download.' => 'Deshabilite cualquier bloqueador de ventanas emergentes en su navegador para garantizar una descarga adecuada',
  'Download exported file' => 'Descargar archivo exportado',
  'Excel 2007+' => 'Excel 2007+',
  'Excel 95 +' => 'Excel 95 +',
  'Export data in selected format' => 'Exportar datos en el formato seleccionado',
  'Exported File' => 'Archivo exportado',
  'Generating the export file. Please wait...' => 'Generando el archivo de exportación. Espere por favor...',
  'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Exportación de cuadrícula generada por el widget Krajee ExportMenu (yii2-export)',
  'HTML' => 'HTML',
  'Hyper Text Markup Language' => 'Lenguaje de marcado de hipertexto',
  'Input error' => 'Error de entrada',
  'Key' => 'Clave',
  'Microsoft Excel 2007+ (xlsx)' => 'Microsoft Excel 2007+ (xlsx)',
  'Microsoft Excel 95+ (xls)' => 'Microsoft Excel 95+ (xls)',
  'Ok to proceed?' => "¿Está bien continuar?",
  'PDF' => 'PDF',
  'Pick from list' => 'Elegir de la lista',
  'Please pick a value from the drop-down list.' => "Elija un valor de la lista desplegable",
  'Portable Document Format' => 'Formato de Documento Portable',
  'Request submitted! You may safely close this dialog after saving your downloaded file.' => '¡Solicitud enviada! Puede cerrar este cuadro de diálogo de forma segura después de guardar el archivo descargado. ',
  'Select Columns' => 'Seleccionar columnas',
  'Select columns to export' => 'Seleccionar columnas para exportar',
  'Tab Delimited Text' => 'Texto delimitado por tabuladores',
  'Text' => 'Texto',
  'The CSV export file will be generated for download.' => "El archivo de exportación CSV se generará para su descarga",
  'The EXCEL 2007+ (xlsx) export file will be generated for download.' => "Se generará el archivo de exportación EXCEL 2007+ (xlsx) para su descarga",
  'The EXCEL 95+ (xls) export file will be generated for download.' => 'El archivo de exportación EXCEL 95+ (xls) se generará para su descarga.',
  'The HTML export file will be generated for download.' => 'El archivo de exportación HTML se generará para su descarga.',
  'The PDF export file will be generated for download.' => 'El archivo de exportación PDF se generará para su descarga.',
  'The TEXT export file will be generated for download.' => 'El archivo de exportación de TEXTO se generará para su descarga.',
  'Value' => 'Valor',
  'Value is not in list.' => 'El valor no está en la lista',
  'grid-export' => 'exportación de cuadrícula',
];
