<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  '<small>Loading &hellip;</small>' => '<small> Cargando & hellip; </small>',
  'Actions' => 'Comportamiento',
  'Active' => 'Activo',
  'Add Book' => 'Agregar libro',
  'All' => 'Todas',
  'Are you sure to delete this {item}?' => "¿Está seguro de eliminar este {artículo}?",
  'Book Listing' => 'Listado de libros',
  'CSV' => 'CSV',
  'Clear selection' => 'Selección clara',
  'Collapse' => 'Colapso',
  'Collapse All' => 'Desplegar todo',
  'Comma Separated Values' => 'Valores Separados por Comas',
  'Delete' => 'Borrar',
  'Disable any popup blockers in your browser to ensure proper download.' => 'Deshabilite cualquier bloqueador de ventanas emergentes en su navegador para garantizar una descarga adecuada.',
  'Download Selected' => 'Descargar seleccionados',
  'Excel' => 'Sobresalir',
  'Expand' => 'Expandir',
  'Expand All' => 'Expandir todo',
  'Export' => 'Exportar',
  'Export All Data' => 'Exportar todos los datos',
  'Export Page Data' => 'Exportar datos de la página',
  'ExportWorksheet' => 'ExportWorksheet',
  'Failed to update editable data due to an unknown server error' => 'No se pudieron actualizar los datos editables debido a un error de servidor desconocido',
  'Generated' => 'Generado',
  'Generating the export file. Please wait...' => 'Generando el archivo de exportación. Espere por favor...',
  'Grid Export' => 'Exportación de cuadrícula',
  'HTML' => 'HTML',
  'Hyper Text Markup Language' => 'Lenguaje de marcado de hipertexto',
  'Inactive' => 'Inactivo',
  'Invalid editable index or model form name' => 'Nombre de formulario de modelo o índice editable no válido',
  'Invalid or bad editable data' => 'Datos editables no válidos o incorrectos',
  'JSON' => 'JSON',
  'JavaScript Object Notation' => 'Notación de objetos JavaScript',
  'Krajee Solutions' => 'Soluciones Krajee',
  'Krajee Yii2 Grid Export Extension' => 'Extensión de exportación de cuadrícula de Krajee Yii2',
  'Library' => 'Biblioteca',
  'Microsoft Excel 95+' => 'Microsoft Excel 95+',
  'No data found' => 'Datos no encontrados',
  'No valid editable model found' => "No se encontró ningún modelo editable válido",
  'Ok to proceed?' => "¿Está bien continuar?",
  'PDF' => 'PDF',
  'PDF export generated by kartik-v/yii2-grid extension' => 'Exportación PDF generada por la extensión kartik-v / yii2-grid',
  'Page' => 'Página',
  'Portable Document Format' => 'Formato de Documento Portable',
  'Request submitted! You may safely close this dialog after saving your downloaded file.' => '¡Solicitud enviada! Puede cerrar este cuadro de diálogo de forma segura después de guardar el archivo descargado. ',
  'Reset Grid' => 'Restablecer cuadrícula',
  'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Cambie el tamaño de las columnas de la tabla como si fuera una hoja de cálculo arrastrando los bordes de la columna.',
  'Show all data' => 'Mostrar todos los datos',
  'Show first page data' => 'Mostrar datos de la primera página',
  'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Mostrando <b> {begin, number} - {end, number} </b> de <b> {totalCount, number} </b> {totalCount, plural, uno {{item}} otro {{items}} }. ',
  'Tab Delimited Text' => 'Texto delimitado por tabuladores',
  'Text' => 'Texto',
  'The CSV export file will be generated for download.' => "El archivo de exportación CSV se generará para su descarga",
  'The EXCEL export file will be generated for download.' => 'El archivo de exportación EXCEL se generará para su descarga.',
  'The HTML export file will be generated for download.' => 'El archivo de exportación HTML se generará para su descarga.',
  'The JSON export file will be generated for download.' => "El archivo de exportación JSON se generará para su descarga",
  'The PDF export file will be generated for download.' => 'El archivo de exportación PDF se generará para su descarga.',
  'The TEXT export file will be generated for download.' => 'El archivo de exportación de TEXTO se generará para su descarga.',
  'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'El resumen de la página muestra SUM para las primeras 3 columnas de cantidad y AVG para la última.',
  'The table header sticks to the top in this demo as you scroll' => "El encabezado de la tabla se pega en la parte superior de esta demostración a medida que se desplaza",
  'There are {totalCount} records. Are you sure you want to display them all?' => 'Hay {totalCount} registros. ¿Estás seguro de que quieres mostrarlos todos?',
  'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Total <b> {count, number} </b> {count, plural, uno {{item}} otro {{items}}}.',
  'Update' => 'Actualizar',
  'View' => 'Vista',
  'Yii2 Grid Export (PDF)' => 'Exportación de cuadrícula de Yii2 (PDF)',
  'export' => 'exportar',
  'grid-export' => 'exportación de cuadrícula',
  'item' => 'Articulo',
  'items' => 'artículos',
  'items-acc' => 'artículos-acc',
  'items-few' => 'artículos-pocos',
  'items-many' => 'artículos-muchos',
  'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
  '© Krajee Yii2 Extensions' => '© Extensiones Krajee Yii2',
];
