<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  '(new)' => '(nuevo)',
  '<h4>Operation Disallowed</h4><hr>Invalid request signature detected during tree data <b>{action}</b> action! Please refresh the page and retry.{params}' => '<h4> Operación no permitida </h4> <hr> Se detectó una firma de solicitud no válida durante la acción <b> {action} </b> de datos del árbol. Actualice la página y vuelva a intentarlo. {params} ',
  'Active' => 'Activo',
  'Add new' => 'Agregar nuevo',
  'Add new root' => 'Agregar nueva raíz',
  'Admin Settings' => 'Configuración de administrador',
  'Already at bottom-most {node} in the hierarchy.' => "Ya está en el último {node} de la jerarquía",
  'Already at left-most {node} in the hierarchy.' => "Ya está en el {node} más a la izquierda de la jerarquía",
  'Already at right-most {node} in the hierarchy.' => "Ya está en el {node} más a la derecha de la jerarquía",
  'Already at top-most {node} in the hierarchy.' => "Ya está en el {node} más alto de la jerarquía",
  'Are you sure you want to remove this {node}?' => "¿Está seguro de que desea eliminar este {node}?",
  'Cannot create {node}. Parent node is not saved or is invalid.' => 'No se puede crear {node}. El node principal no está guardado o no es válido. ',
  'Cannot move root level {nodes} before or after other root level {nodes}.' => 'No se puede mover el nivel de raíz {nodes} antes o después de otro nivel de raíz {nodes}.',
  'Cannot move this {node} as the {node} details are not saved yet.' => "No se puede mover este {node} porque los detalles del {node} aún no se han guardado",
  'Child Allowed' => 'Permitido para niños',
  'Clear search results' => 'Borrar resultados de búsqueda',
  'Collapsed' => 'Colapsado',
  'Default' => 'Defecto',
  'Delete' => 'Borrar',
  'Depth' => 'Profundidad',
  'Disabled' => 'Discapacitado',
  'Error removing the {node}. Please try again later.' => 'Error al eliminar el {node}. Por favor, inténtelo de nuevo más tarde.',
  'Error while creating the {node}. Please try again later.' => 'Error al crear el {node}. Por favor, inténtelo de nuevo más tarde.',
  'Error while moving the {node}. Please try again later.' => 'Error al mover el {node}. Por favor, inténtelo de nuevo más tarde.',
  'Error while removing the {node}. Please try again later.' => 'Error al eliminar el {node}. Por favor, inténtelo de nuevo más tarde.',
  'Error while saving the {node}. Please try again later.' => 'Error al guardar el {node}. Por favor, inténtelo de nuevo más tarde.',
  'Error while viewing the {node}. Please try again later.' => 'Error al ver el {node}. Por favor, inténtelo de nuevo más tarde.',
  'ID' => 'ID',
  'Icon' => 'Icono',
  'Icon Type' => 'Tipo de icono',
  'Left' => 'Izquierda',
  'Movable Down' => 'Movable Down',
  'Movable Left' => 'Móvil a la izquierda',
  'Movable Right' => 'Derecha móvil',
  'Movable Up' => 'Movable Up',
  'Move Down' => 'Mover hacia abajo',
  'Move Left' => 'Mover hacia la izquierda',
  'Move Right' => 'Moverse a la derecha',
  'Move Up' => 'Ascender',
  'Name' => 'Nombre',
  'No valid {nodes} are available for display. Use toolbar buttons to add {nodes}.' => 'No hay {nodes} válidos disponibles para mostrar. Use los botones de la barra de herramientas para agregar {nodes}. ',
  'Read Only' => 'Solo lectura',
  'Refresh' => 'Actualizar',
  'Removable' => 'Retirable',
  'Removable (with children)' => 'Removible (con niños)',
  'Reset' => 'Reiniciar',
  'Right' => 'Derecha',
  'Root' => 'Raíz',
  'Save' => 'Guardar',
  'Saved the {node} details successfully.' => "Se guardaron los detalles de {node} correctamente",
  'Search...' => 'Buscar...',
  'Select a {node} by clicking on one of the tree items.' => 'Seleccione un {node} haciendo clic en uno de los elementos del árbol',
  'Select...' => 'Seleccione...',
  'Selected' => 'Seleccionado',
  'The selected {node} cannot be moved.' => 'El {node} seleccionado no se puede mover.',
  'The untitled {node} was removed.' => "Se eliminó el {node} sin título",
  'The {node} was moved successfully.' => "El {node} se movió correctamente",
  'The {node} was removed successfully.' => "El {node} se eliminó correctamente",
  'The {node} was successfully created.' => "El {node} se creó correctamente",
  'This operation is not allowed.' => 'Esta operación no está permitida',
  'Untitled' => 'Intitulado',
  'Visible' => 'Visible',
  'You cannot add children under this {node}.' => 'No puede agregar niños bajo este {node}.',
  'node' => 'node',
  'nodes' => 'nodes',
  '{node} # {id} - \'{name}\': {error}' => '{node} # {id} - \'{name}\': {error}',
];
