<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  '\'{class}\' must extend from \'yii
bacRule\' or its child class' => '\'{class}\' debe heredarse desde \' yii
bacRule \'o su clase hija',
  'Activate' =>  'Activar',
  'Add' =>  'Agregar',
  'Admin' =>  'Administración',
  'Application' =>  'Solicitud',
  'Are you sure to delete this item?' =>  "¿Está seguro de eliminar este elemento?",
  'Are you sure you want to activate this user?' =>  "¿Está seguro de que desea activar este usuario?",
  'Assign' =>  'Asignar',
  'Assigned users' =>  'Usuarios asignados',
  'Assignment' =>  'Asignación',
  'Assignments' =>  'Asignaciones',
  'Change' =>  'Cambio',
  'Change Password' =>  'Cambiar la contraseña',
  'Class Name' =>  'Nombre de la clase',
  'Create' =>  'Crear',
  'Create Menu' =>  'Crear menú',
  'Create Rule' =>  'Crear regla',
  'Create label' =>  'Crear etiqueta',
  'Data' =>  'Datos',
  'Delete' =>  'Borrar',
  'Description' =>  'Descripción',
  'Help' =>  'Ayudar',
  'ID' =>  'ID',
  'Invalid rule "{value}"' =>  'Regla no válida "{value}"',
  'Login' =>  'Acceso',
  'Menus' =>  'Menús',
  'Name' =>  'Nombre',
  'New route(s)' =>  'Nueva (s) ruta (s)',
  'Order' =>  'Pedido',
  'Parent' =>  'Padre',
  'Parent Name' =>  'Nombre del padre',
  'Remove' =>  'Eliminar',
  'Reset' =>  'Reiniciar',
  'Route' =>  'Ruta',
  'Routes' =>  'Rutas',
  'Rule "{value}" does not exists' =>  'La regla "{value}" no existe',
  'Rule Name' =>  'Nombre de la regla',
  'Rules' =>  'Reglas',
  'Save' =>  'Guardar',
  'Search' =>  'Buscar',
  'Search for assigned' =>  'Buscar asignados',
  'Search for available' =>  'Buscar disponibles',
  'Send' =>  'Enviar',
  'Signup' =>  'Inscribirse',
  'Type' =>  'Tipo',
  'Unknown class \'{class}\'' =>  'Clase desconocida \'{class}\'',
  'Update' =>  'Actualizar',
  'Update Menu' =>  'Menú de actualización',
  'Update Rule' =>  'Actualizar regla',
  'Update label' =>  'Actualizar etiqueta',
  'Username' =>  'Nombre de usuario',
  'Users' =>  'Usuarios',
];
